channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - bokeh==2.4.2
  - cudatoolkit==11.1.74
  - ffmpeg==4.3
  - jupyter_client
  - pillow==8.0.1
  - python==3.9
  - pip:
    - black
    - coroica==0.1.25
    - joblib==1.0.1
    - jupyter==1.0.0
    - jupyterlab-widgets==1.0.0
    - matplotlib==3.4.3
    - mne==1.0
    - numpy
    - packaging==21.3
    - pandas==1.4.2
    - papermill==2.3.3
    - pipreqs==0.4.10
    - pymongo==3.11.4
    - python-picard==0.4
    - pytz==2021.1
    - sacred==0.8.2
    - scikit-learn==1.1.3
    - scipy==1.8.0
    - seaborn==0.11.1
    - setuptools==58.0.4
    - statsmodels==0.13.2
    - tqdm==4.60.0
    - traitlets==5.0.5

